FROM docker.io/library/ubuntu:latest

RUN set -eux; \
	apt-get update; \
	DEBIAN_FRONTEND=noninteractive apt-get install -y mawk- gawk make doxygen help2man; \
	rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src
